name: mercypartners
favicon: null
layout_spectrum: 0.04168360051698983
typography_spectrum: 0.5735117117874324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2450864422135055
  lightness: 0.7953290157020092
  saturation: 0.661837842548266
  rhythmicContrast: 0.0987465912476182
purpose: []
